[entities]

# Prion diseases
Generic_Prion
sCJD
sFI
VPSPr
fCJD
GSS
FFI
vCJD
iCJD
Kuru
Differential_Diagnosis

# Symptoms / findings
Symptom

# Test names
Imaging_test
Electrophysio_test
Blood_biomarker_test
Genetic_test
Molecular_assay
Autopsy

# Test targets
Imaging_target
Electrophysio_target
Blood_biomarker_target
Genetic_test_target
Molecular_assay_target
Autopsy_target

# Anatomy
Anatomic_location

# Test result
Test_result

# Age
Age

# Treatment
Treatment

# Complication
Complication

# Time
Duration
Time_point

# Statistics
Sensitivity
Specificity
Prevalence
Incidence
Number

# Choose Related
Choose_Related

# Choose Done
Choose_Done
